### ISSUE TITLE
Unable to resolve node_modules

### ISSUE THREAD

**Issue by GroupXTech** [shahen94/react-native-switch#1]
I'm certain it's there, but I still have unable to resolve Module React from path/to/node_modules/react-native-switch/lib/Switch.js Unable to find this module in its module map or any of the node modules directory....

I've even tried removing the node_modules then reinstalling everything. Just to make sure...

Any ideas?
Thanks in advance... I've been looking all over for a switch like yours

**Comment by shahen94** [comment]
Hi @GroupXTech . Please try again and install the latest version.
I updated Switch.js.
https://github.com/shahen94/react-native-switch/commit/aa4825906af98bdd4a20a62dc03f3f42a69f1e01

**Comment by GroupXTech** [comment]
figured it out...

you have a big 'R' in react
import React, { Component, PropTypes } from 'react'

**Comment by GroupXTech** [comment]
It's the little things in life... isn't it ;-)
