### ISSUE TITLE
Proptypes completely removed 

### ISSUE THREAD

**Issue by RameshkrishnanV** [shahen94/react-native-switch#10]
PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead.

**Comment by shahen94** [comment]
Hi @RameshkrishnanV !
Yes you're right, i have no time to work on this lib in these days, but if you'd like to open PR i'll take a look.

**Comment by leecrossley** [comment]
I've just submitted a PR for this #12
