### ISSUE TITLE
how to change container's width?

### ISSUE THREAD

**Issue by JulioOrellana** [shahen94/react-native-switch#11]
I need to change switch container's switch. How can I achieve that?
![screen shot 2017-08-31 at 11 42 54 am](https://user-images.githubusercontent.com/10372340/29929315-8a72a20c-8e41-11e7-9a94-4fe8f6135b1f.png)

Thanks!

**Comment by shahen94** [comment]
https://github.com/shahen94/react-native-switch/issues/8
