### ISSUE TITLE
Incompatibile with Expo SDK v22.0.0+

### ISSUE THREAD

**Issue by htbkoo** [shahen94/react-native-switch#19]
First of all, thanks for creating this component! :)
It provides much better flexibility to me than the native switch.

However, I believe that it is currently incompatible with the Expo SDK for version newer than v22.0.0 because of the usage of "**View.propTypes.style**".
The details are stated [here in this expo blog](https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6):

> If you, or any libraries that you use. use View.propTypes.style you will need to change that to ViewPropTypes.style. You will only see errors for this in production — so be sure to test your app with development mode disabled.

Locally I had tried to update accordingly and it worked for me. 

Are there any plans to update this component?
I can create a pull request for this change if you do not mind. :)

**Comment by shahen94** [comment]
Hi @htbkoo !
Good catch, yeah `View.propTypes` was a long time deprecated and not it's removed from rn core.
If you could submit a PR I'll merge it right away.

Thanks.

**Comment by htbkoo** [comment]
No problem. Have created #20 for this.
And thanks for the prompt reply. ;)
