### ISSUE TITLE
Value prop not respected properly

### ISSUE THREAD

**Issue by grit96** [shahen94/react-native-switch#39]
I can't treat the switch as a controlled component. I have a component with `value` state and `onValueChange` method that are passed as props to the switch. If I set the `value` to `false` in the `onValueChange`, then do something before setting the `value` to `true` (or don't set it to `true` at all), the switch is in the visible `on` state even though `value` is `false`.

Example:

```js
class Test extends Component {
  state = {
	value: false
  };

  onValueChange = (value: boolean) => {
	console.log(value);
	doSomeAsync((err) => {
	  if (err) {
		this.setState({ value: false });
	  } else {
		this.setState({ value });
	  }
	});
  }

  render() {
    const {
      state: { value },
      onValueChange
    } = this;

    return (
		<Switch
          value={value}
          onValueChange={onValueChange}
        />
    );
  }
}
```

**Comment by vdanylov** [comment]
Yeap, have the some(

**Comment by enigmasteron** [comment]
Maybe this help you

`if (disabled) {
      return;
    }

    if (this.props.value === this.state.value) {
      onValueChange(!this.state.value);
      return;
    }`

**Comment by vdanylov** [comment]
> Maybe this help you, add this in switch.js file (112 line)
> 
> ```ts
> if (disabled) {
>   return;
> }
> if (this.props.value === this.state.value) {
>   onValueChange(!this.state.value);
>   return;
> }
> ```

Thanks

**Comment by dev3288** [comment]
Still the same issue, no update yet ?

**Comment by raphaelpinel** [comment]
@vdanylov why didn't you create a Pull Request? I had the same issue and your answer works
