### ISSUE TITLE
In ios switch is not hiding off text

### ISSUE THREAD

**Issue by jariwalabhavesh** [shahen94/react-native-switch#4]
Specific issue with ios

Switch is look like 

When switch is off, it looks like

![screen shot 2017-02-27 at 11 43 23 am](https://cloud.githubusercontent.com/assets/10993666/23350670/2eff8610-fce2-11e6-910f-8a291c747762.png)

When switch is on, it looks like

![screen shot 2017-02-27 at 11 43 12 am](https://cloud.githubusercontent.com/assets/10993666/23350679/3fb6376a-fce2-11e6-8f29-b0c09e99a39b.png)

Off text is visible outside of switch

It is also visible in gif image that you provide, because background is white and text in also white it is not properly visible

![screen shot 2017-02-27 at 11 46 34 am](https://cloud.githubusercontent.com/assets/10993666/23350819/3fa612bc-fce3-11e6-9700-ad5853e5d2f5.png)

**Comment by shahen94** [comment]
Thank you for reporting, 
On which RN version do you use it ?

**Comment by jariwalabhavesh** [comment]
@shahen94 
Thanks for responding
I am using RN 0.34.0

**Comment by shahen94** [comment]
Yes, really. Seems like we have to add `overflow: hidden` style  to root animated view.

**Comment by jariwalabhavesh** [comment]
@shahen94 
 I had tested it and it is working fine :-)

Thanks you @shahen94, so much for such a quick response

**Comment by shahen94** [comment]
@jariwalabhavesh I'm going to close this issue, so feel free to reopen this if you'll have this issue again

**Comment by jariwalabhavesh** [comment]
@shahen94 : it is working for me after adding overflow:hidden to parent view. 
It is okay beacuse it is working with latest RN version
