### ISSUE TITLE
ActiveText no changing

### ISSUE THREAD

**Issue by r4doshka** [shahen94/react-native-switch#40]

**Comment by r4doshka** [comment]
activeText prop change nothing, text all times 'activeText' 

![2018-05-22 15 58 56](https://user-images.githubusercontent.com/13236408/40355865-5494c2a6-5dd9-11e8-9dfc-7aafc5811a20.png)
![2018-05-22 15 59 27](https://user-images.githubusercontent.com/13236408/40355866-54e0499c-5dd9-11e8-8510-a2ea76d6eefd.png)
![2018-05-22 15 59 55](https://user-images.githubusercontent.com/13236408/40355868-5554b11a-5dd9-11e8-9421-6b3770ef91a0.png)

**Comment by shahen94** [comment]
Can you please try master version instead of using npm

**Comment by shackra** [comment]
that solves it for me

**Comment by shahen94** [comment]
Great!
Closing this.

**Comment by chetan-plrch** [comment]
activeText is hardcoded in source code, please change it to the variable **activeText**.
