### ISSUE TITLE
NPM Outdated

### ISSUE THREAD

**Issue by rjerue** [shahen94/react-native-switch#62]
NPM is outdated vs. the source. 

There's also a bit of breakage as both default values have changed, notably renderActiveText: false, and renderInActiveText: false

**Comment by smcilhargey** [comment]
Additionally, it's activeText value is broken.

**Comment by shahen94** [comment]
Correct - versions are different.
You can wait for a new deployment soon.

**Comment by MaximilienMeyer** [comment]
Hi @shahen94 ,

Up for this 

Thanks for sharing your lib !
