### ISSUE TITLE
how to change size of {width,height} ？

### ISSUE THREAD

**Issue by 12343954** [shahen94/react-native-switch#8]
RT

:) thank you 👍

**Comment by shahen94** [comment]
hi @12343954 .
Right now we don't have an ability to change width/height,
https://github.com/shahen94/react-native-switch/blob/master/lib/Switch.js#L136

Switch size calculated by some formula, but anyway you can fork and add an ability to feed width/height through props

**Comment by 12343954** [comment]
@shahen94 
all right , thank you all the same !

**Comment by layerok** [comment]
Actually you can change width. I found workaround for it
```
export const Toggle = () => {
  const toggleWidth = 40;
  const circleSize = 18;
  const switchWidthMultiplier = toggleWidth / circleSize;
  const multiplierFix = circleSize / (((circleSize * switchWidthMultiplier) - circleSize) / 2)
  return <Switch 
                 value={true}
                 circleSize={circleSize}
                 switchLeftPx={multiplierFix}
                 switchRightPx={multiplierFix}
                 switchWidthMultiplier={switchWidthMultiplier}
  />
}
```
